controllers/SupevisorController.php
<?php

/*
 * This controller handle all supevisor wise controls
 * @author: Vikum
 * @date: 27/06/2017
 * 
 */

namespace app\controllers;

//defined('BASEPATH') OR exit('No direct script access allowed');


use Yii;
use yii\db\ActiveRecord;
use yii\web\Controller;
use app\models\Customer;
use app\models\call_center_user;
use app\models\Agent_requests;
use app\models\agent_notifications;
use app\models\web_presence;
use app\models\Miss_calls_email_log;
use app\models\cdr;
use app\models\Call_records;
use app\models\Contact_list;
use app\models\Logged_in_users;
use app\models\Ext_queue_intermediate;
use app\models\Extension_queue;
use app\models\Allowed_exec_extqueues;
use app\models\missed_calls_email_subscribers;

class SupevisorController extends Controller {

    /**
     * <b>Overrides parent class controller constructor</b>
     * 
     * @param type $id
     * @param type $module
     * @param type $config
     * 
     * @author Sandun
     * @since 2017-09-25
     */
    public function __construct($id, $module, $config = array()) {
        parent::__construct($id, $module, $config);
//        if (!Yii::$app->session->has('user_id')) {
//            $this->redirect('index.php?r=user/login_view');
//        } else if (Yii::$app->session->get('user_role') == '2' || Yii::$app->session->get('user_role') == '4') {
//            // user is and agent or super agent
//            $this->redirect('index.php?r=user/login_view');
//        }
    }

//    public function __construct() {
//
//        parent::__construct();
//    }

    public function actionOverview() {
        $session = Yii::$app->session;
        if (!$session->has('user_id')) {
            $this->redirect('index.php?r=user/login_view');
        } else {
            $user_role = $session->get('user_role');
            if ($user_role == '1' || $user_role == '3' || $user_role == '5') {
                $query_customers = Customer::find();
                $liveCalls = $query_customers->all();
                $webphoneParams = require(__DIR__ . '/../config/webphone.php');
                $webphoneParams['username'] = Yii::$app->session->get('voip');
                $webphoneParams['phoneState'] = call_center_user::getAgentWebphoneState($session->get('user_id'));
                $contacts = $this->allcontacts();

                $consumedAgentRequest = Agent_requests::getConsumedAgentRequestsBySupervisor();
                $requestData = array();
                $i = 0;
                foreach ($consumedAgentRequest as $key) {
                    $agentInfoRequest = call_center_user::getUser($key['agent_id']);
//                $type = $key['request_type'];
                    $tempAgentData = array(
                        'type' => $key['request_type'],
                        'id' => $key['id'],
                        'name' => $agentInfoRequest[0]['name'],
                    );
                    array_push($requestData, $tempAgentData);
//                    $requestData[$i]['type'] = $key['request_type'];
//                    $requestData[$i]['id'] = $key['id'];
//                    $requestData[$i]['name'] = ;
//                    $requestData[$i]['time'] = $key['approved_time_period'];
                    $i++;
                }
                return $this->render('coordinatorOverview', ['liveCalls' => $liveCalls, 'webphoneParams' => $webphoneParams, 'contacts' => $contacts, 'agentRequests' => $requestData]);
            } else {
                $this->redirect('index.php?r=user/login_view');
            }
        }
    }

    public function actionNotifyagent() {
        $notify_type = $_POST['dial_type'];
        $agent_id = $_POST['agent_id'];

        $session = Yii::$app->session;
        $supervisor_id = $session->get('user_id');

        $time = date("Y-m-d H:i:s");
        $notif_status = 'active';

        $agent_notif = new agent_notifications();
        $agent_notif->agent_id = $agent_id;
        $agent_notif->supervisor_id = $supervisor_id;
        $agent_notif->notif_type = $notify_type;
        $agent_notif->notif_status = $notif_status;
        $agent_notif->notif_time = $time;
        $insert = $agent_notif->insert();

        echo $insert;
    }

    public function actionGetuser() {
        $customerId = $_POST['q'];
        $customerInfo = Customer::getCustomerInformation($customerId);
        $fullDate = $customerInfo[0]['dob'];
        $pieces = explode(" ", $fullDate);
        // piece1
        $customerData = array(
            'customer_name' => $customerInfo[0]['customer_name'],
            'email' => $customerInfo[0]['email'],
            'contact' => $customerInfo[0]['contact_number'],
            'address' => $customerInfo[0]['address'],
            'dob' => $pieces[0],
            'gender' => $customerInfo[0]['gender'],
        );


        echo json_encode($customerData);
    }

    // This function loads Agent data according to the supervisor rank
    public function actionManage() {
        return $this->render('manageUsers');
    }

    public function actionManagetable() {
        $session = Yii::$app->session;
        $user_role = $session->get('user_role');
        if (!$session->has('user_id') || $user_role == '2' || $user_role == '4') {
//            echo $user_role . ' ++++';
//            echo $user_role.' ';            
            $this->redirect('index.php?r=user/login_view');
        } else {

            $userInfo = call_center_user::getUserData($user_role);
            $liveAgents = Logged_in_users::getLoggedAgents();
//            print_r($userInfo);
            $result = array();
            for ($i = 0; $i < count($userInfo); $i++) {
//                echo 'Hello '.$userInfo[$i]['name'];
                $result[$i]['id'] = $userInfo[$i]['id'];
                $result[$i]['name'] = $userInfo[$i]['name'];
                $result[$i]['fullname'] = $userInfo[$i]['fullname'];
                $result[$i]['voip'] = $userInfo[$i]['voip_extension'];
                $result[$i]['role_id'] = $userInfo[$i]['role_id'];
                $result[$i]['status'] = $userInfo[$i]['status'];
                $result[$i]['webphone'] = $userInfo[$i]['webphone'];
            }
            $onlineUsers = array();
            if (count($liveAgents) > 0) {
                foreach ($liveAgents as $key) {
                    array_push($onlineUsers, $key['user_id']);
                }
            }


            return $this->render('manageUsersTable', ['user_data' => $result, 'liveAgents' => $onlineUsers]);
        }
//        return $this->render('manageUsersTable');
    }

    public function actionInsert() {
        $this->checksession();
        $user = 'null';
        $userInfo = array();
        $availableExtensions = $this->getAvailableVOIPExtensions();
        //to get all queues
        $availableQueus = Extension_queue::getAllAvailableQueuesData();

        if (isset($_GET['user'])) {
            $id = $_GET['user'];
            $allowedQueues = Extension_queue::getAllAvailableQueuesDataOfSelectedExecutive($id);
            $QueueOfSupervisor = Extension_queue::getExtensionQueueIdOfTheSupervisor($id);
            if(Yii::$app->session->get("user_role") != "1"){
                // not admin
                if(Yii::$app->session->get("user_role") == "3" || Yii::$app->session->get("user_role") == "5"){
                    // is a supervisor
                    $agentIdsOfQueue = call_center_user::getAgentIdsFromQueueId(Yii::$app->session->get("extQueueId"));
                    if(in_array($id, $agentIdsOfQueue) == FALSE){
                        // the agent details not belong to the viewing person, redirects to manage users page
                        return $this->redirect("index.php?r=supevisor/manage");
                    }
                }else{
                    // is not a supervisor
                    return $this->redirect("index.php?r=user/login_view");
                }
            }
            $userInfo = call_center_user::getUser($id);
            $result = array(
                'id' => $userInfo[0]['id'],
                'name' => $userInfo[0]['name'],
                'fullname' => $userInfo[0]['fullname'],
                'role_id' => $userInfo[0]['role_id'],
                'extension' => $userInfo[0]['voip_extension'],
                'user_profile_pic' => $userInfo[0]['user_profile_pic']
            );

//            if (count($availableExtensions) > 0) {
            array_push($availableExtensions, $userInfo[0]['voip_extension']);
            sort($availableExtensions);
//            }else{
//                $availableExtensions = array();
//            }


            return $this->render('addNewUser', ['user_data' => $result, 'availableExtensions' => $availableExtensions, 'availableQueus'=> $availableQueus, 'allowedQueues'=>$allowedQueues, 'QueueOfSupervisor' => $QueueOfSupervisor ]);
        } else {
            return $this->render('addNewUser', ['user_data' => array('id' => '', 'name' => '', 'fullname' => '', 'role_id' => '', 'extension' => '', 'user_profile_pic' => ''), 'availableExtensions' => $availableExtensions, 'availableQueus'=> $availableQueus, 'allowedQueues'=>[], 'QueueOfSupervisor' => []]);
        }





//        return $this->render('addNewUser');
    }

    /**
     * <b>Get all available extension numbers</b>
     * <p>This function returns all the available extension numbers sorted by assending order.
     * If no available extensions, will return 0 </p>
     * 
     * @return array available VOIP Extension numbers / 0
     * @since 2017-08-04
     * @author Sandun
     */
    private function getAvailableVOIPExtensions() {
//    public function actionGetavailableextensions() {
        $allExtensions = web_presence::getAllVoipExtensions();
        $takenExtensions = call_center_user::getAllAssignedVOIPExtensions();

        $availableExtentions = array_diff($allExtensions, $takenExtensions);
        if (count($availableExtentions) > 0) {

views/supevisor/addNewEmail.php
<?php
use yii\helpers\Url;
?>


<?php 

$data = 0;
if (isset($emailInfo)) {
    $data = $emailInfo;
}


?>
<body>
    <div class = "container-fluid">
        <div class = "row">
            <div class = "col-md-12">
                <a href = "<?= Url::to(['supevisor/manageemail']); ?>" class = "btn btn-info btn-sm" type = "button">< Back</a>
                <h3 class = "text-primary text-center">
                    <?php if ($data != 0) { ?>
                        <b> Update Email </b>
                    <?php }else{ ?>
                        <b> Add New Email </b>
                    <?php } ?>
                </h3>
                <!-- <form action="#" role = "form" id = "idNewEmailForm"> -->
                    <div class = "form-group">

                        <label>
                            Subscriber Name<span style="color: tomato">*</span>
                        </label>
                        <input type = "text" class = "form-control" id = "subname" name = "subname" <?php if ($data !=0) { ?> value = "<?=$data[0]['subsciber_name']?>" <?php } ?> />
                        <br>
                        <label>
                            Email Address<span style="color: tomato">*</span>
                        </label>
                        <input type = "text" class = "form-control" id = "emailaddress" name = "emailaddress" <?php if ($data !=0) { ?> value = "<?=$data[0]['email_address']?>" <?php } ?>/>                            
                        <span id="emailValidationMessage"></span>
                    </div>


                    <a id = "btnSaveExtension" class = "btn btn-success btn-md disabled" onclick="validateForm()">
                        <?php if ($data !=0) { ?> Update <?php }else{ ?> Save <?php } ?>
                    </a>
                    <a class = "btn btn-info" onclick="clearForm()">
                        Clear
                    </a>

                    <!-- </form> -->

                </div>
            </div>
            <br>
            <div class="row" id="notficationDiv">
            </div>
        </div>
    </body>
    <script>


        $("document").ready(function(){
            <?php if ($data == 0 ) { ?>
                clearForm();
            <?php }else{ ?>
                $("#subname").val("<?=$data[0]['subsciber_name']?>");
                $("#emailaddress").val("<?=$data[0]['email_address']?>");
            <?php } ?>    
        });

        var isEmailExists = true;

        $("#emailaddress").keypress(function(event) {
           pressEnter(event);
       });

        function pressEnter(event) {
            if (event.keyCode == 13) {
                $("#btnSaveExtension").click();
            }
        }

        function showSaveSuccessMessage(){
           $("#notficationDiv").empty();
           var successMsgDiv = $("<div></div>");
           $(successMsgDiv).addClass("alert alert-success");
           $(successMsgDiv).append("<strong> Email Saved Successfully!</strong>");
           $("#notficationDiv").append(successMsgDiv);
       }

       function showSaveFailedMessage(){
           $("#notficationDiv").empty();
           var failMsgDiv = $("<div></div>");
           $(failMsgDiv).addClass("alert alert-danger");
           $(failMsgDiv).append("<strong> Email Saving Failed!</strong> Please try saving again");
           $("#notficationDiv").append(failMsgDiv);
       }


        function showUpdateSuccessMessage(){
           $("#notficationDiv").empty();
           var successMsgDiv = $("<div></div>");
           $(successMsgDiv).addClass("alert alert-success");
           $(successMsgDiv).append("<strong> Email Updated Successfully!</strong>");
           $("#notficationDiv").append(successMsgDiv);
       }

       function showUpdateFailedMessage(){
           $("#notficationDiv").empty();
           var failMsgDiv = $("<div></div>");
           $(failMsgDiv).addClass("alert alert-danger");
           $(failMsgDiv).append("<strong> Email Updating Failed!</strong> Please try saving again");
           $("#notficationDiv").append(failMsgDiv);
       }


       function addNewEmailInfo(){
        var subname = $("#subname").val();
        var emailaddress = $("#emailaddress").val();

        $.ajax({
            url: "<?= Url::to(['supevisor/addnewemailajax'])?>",
            type: 'POST',
            data: {subname : subname,emailaddress:emailaddress},
            success: function (data, textStatus, jqXHR) {
                if(data == "1"){
                   showSaveSuccessMessage();
                   clearForm();
               }else{
                  showSaveFailedMessage();
              }
          },
          error: function (jqXHR, textStatus, errorThrown) {
           showSaveFailedMessage();
       }
   });

    }


    function updateEmailInfo(){
        var id = "<?=$data[0]['id']?>";
        var subname = $("#subname").val();
        var emailaddress = $("#emailaddress").val();

        console.log(id);
        console.log(subname);
        console.log(emailaddress);

        $.ajax({
            url: "<?= Url::to(['supevisor/updateemailajax'])?>",
            type: 'POST',
            data: {id:id,subname : subname,emailaddress:emailaddress},
            success: function (data, textStatus, jqXHR) {
                if(data == "1"){
                   showUpdateSuccessMessage();
                   setTimeout(function(){ location.reload(); }, 1000);                   
               }else{
                  showUpdateFailedMessage();
              }
          },
          error: function (jqXHR, textStatus, errorThrown) {
           showUpdateFailedMessage();
       }
   });

    }


    function validateForm(){
        var validationSuccess = true;
        if($("#emailaddress").val() == ""){
                // Queue name is empty
                if(validationSuccess == true){
                    validationSuccess = false;
                    swal({
                        title: 'Oops!',
                        text: 'Email Address is empty!',
                        type: "warning"
                    });
                }
            }

            if($("#subname").val() == ""){
                // Queue name is empty
                if(validationSuccess == true){
                    validationSuccess = false;
                    swal({
                        title: 'Oops!',
                        text: 'Subscriber Name is empty!',
                        type: "warning"
                    });
                }
            }

            
            if(validationSuccess == true){
            	if(isEmailExists == false){

                    <?php if ($data == 0 ) { ?>
                        addNewEmailInfo();
                    <?php }else{ ?>
                        updateEmailInfo();
                    <?php } ?>   


                }else{
                 swal({
                    title: 'Oops!',
                    text: 'Email Address already exists!',
                    type: "warning"
                });
             }
         }

     }          


     function clearForm(){
        $("#subname").val("");
        $("#emailaddress").val("");
        $("#emailValidationMessage").html("");
    }

    $("#emailaddress").keyup(function(){
        var typingText = $(this).val();
        var validatedEmail = validateEmail(typingText);
        var valform = true;
        var currentEmail = null;
            <?php if ($data != 0 ) { ?>
                currentEmail ="<?=$data[0]['email_address']?>";
            <?php } ?>


        if (!validatedEmail) {
            $("#emailValidationMessage").html("Email Address Is Not Valid");
            $("#emailValidationMessage").css("color", "red");  
            $("#btnSaveExtension").addClass("disabled");
            valform = false
        }

        if(typingText != ""  && valform){
                // typing text is not empty
                // $("#emailValidationMessage").html("Checking..");
                // $("#emailValidationMessage").css("color", "black");  
                $("#btnSaveExtension").addClass("disabled");

                $.ajax({
                    url: "<?= Url::to(['supevisor/checkemailavailability'])?>",
                    data: {typingText : typingText},
                    type: 'GET',
                    success: function (data, textStatus, jqXHR) {
                        if(data == "1"){
                            $("#emailValidationMessage").html("");
                            $("#emailValidationMessage").css("color", "green");
                            $("#btnSaveExtension").removeClass("disabled");
                            isEmailExists = false;
                        }else{
                            if (currentEmail == typingText) {
                                $("#emailValidationMessage").html("");
                                $("#emailValidationMessage").css("color", "red");  
                                $("#btnSaveExtension").removeClass("disabled");   
                                isEmailExists = false;                             
                            }else{
                                $("#emailValidationMessage").html("Email Address Already Exists");
                                $("#emailValidationMessage").css("color", "red");  
                                $("#btnSaveExtension").addClass("disabled");
                                isEmailExists = true;
                            }
                        }
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        console.log("extension validation error : "+jqXHR.responseText);
                        isEmailExists = true;
                    }
                });    
            }else{
                // typing text is empty
                $("#emailValidationMessage").html("");
                $("#emailValidationMessage").css("color", "red");  
                $("#btnSaveExtension").addClass("disabled");
            }
        });


    function validateEmail(email) {
        var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
        return re.test(String(email).toLowerCase());
    }        


</script>

views/supevisor/addNewExtension.php
<?php
use yii\helpers\Url;
?>

<body>
    <div class = "container-fluid">
            <div class = "row">
                <div class = "col-md-12">
                <a href = "<?= Url::to(['supevisor/manage']); ?>" class = "btn btn-info btn-sm" type = "button">< Back</a>
                    <h3 class = "text-primary text-center">
                        <b> Add New Extension </b>
                    </h3>
                    <!-- <form action="#" role = "form" id = "idNewExtensionForm"> -->
                        <div class = "form-group">

                            <label>
                                New VOIP Extension Number<span style="color: tomato">*</span>
                            </label>
                            <input type = "number" class = "form-control" id = "extensionNumberInput" name = "extensionNumberInput" />
                            <span id="extensionValidationMessage"></span>
                        </div>


                        <a id = "btnSaveExtension" class = "btn btn-success btn-md disabled" onclick="validateForm()">
                            Save
                        </a>
                        <a class = "btn btn-info" onclick="clearForm()">
                            Clear
                        </a>

                    <!-- </form> -->

                </div>
            </div>
            <br>
            <div class="row" id="extInsertNotifDiv">
            </div>
    </div>
</body>
<script>
		var isExtensionExists = true;

		$("#extensionNumberInput").keypress(function(event) {
			pressEnter(event);
		});

		function pressEnter(event) {
            if (event.keyCode == 13) {
                $("#btnSaveExtension").click();
            }
        }

		function showSaveSuccessMessage(extension){
			$("#extInsertNotifDiv").empty();
			var successMsgDiv = $("<div></div>");
			$(successMsgDiv).addClass("alert alert-success");
			$(successMsgDiv).append("<strong> "+ extension +" Extension Saved Successfully!</strong>");
			$("#extInsertNotifDiv").append(successMsgDiv);
		}

		function showSaveFailedMessage(extension){
			$("#extInsertNotifDiv").empty();
			var failMsgDiv = $("<div></div>");
			$(failMsgDiv).addClass("alert alert-danger");
			$(failMsgDiv).append("<strong> "+ extension +" Extension Saving Failed!</strong> Please try saving again");
			$("#extInsertNotifDiv").append(failMsgDiv);
		}

        function addNewExtensionAjax(){
            var extensionNumber = $("#extensionNumberInput").val();
            
            $.ajax({
                url: "<?= Url::to(['supevisor/addnewextensionajax'])?>",
                type: 'POST',
                data: {extension : extensionNumber},
                success: function (data, textStatus, jqXHR) {
                    if(data == "1"){
                        // swal({
                        //     title: 'Added!',
                        //     text: 'New extension added successfully',
                        //     type: "success"
                        // });
            			showSaveSuccessMessage(extensionNumber);
                        clearForm();
                }else{
                    // swal({
                    //     title: 'Some problem!',
                    //     text: 'An error occured, Please re submit your new extension!',
                    //     type: "danger"
                    // });
            		showSaveFailedMessage(extensionNumber);
                }
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    // alert(jqXHR.responseText);
                    // swal({
                    //     title: 'Some problem!',
                    //     text: 'An error occured, Please re submit your new extension!',
                    //     type: "danger"
                    // });
					showSaveFailedMessage(extensionNumber);
                }
            });
            
        }
        
        
        function validateForm(){
            var validationSuccess = true;
            if($("#extensionNumberInput").val() == ""){
                // Queue name is empty
                if(validationSuccess == true){
                    validationSuccess = false;
                        swal({
                            title: 'Oops!',
                            text: 'Extension Number is empty!',
                            type: "warning"
                        });
                }
            }

            
            if(validationSuccess == true){
            	if(isExtensionExists == false){
                // successfully validated
                	addNewExtensionAjax();
            	}else{
					swal({
                        title: 'Oops!',
                        text: 'Extension Number already exists!',
                        type: "warning"
                    });
            	}
            }
            
            function clearForm(){
                $("#extensionNumberInput").val("");
            }
        }
        
        $("#extensionNumberInput").keyup(function(){
            var typingText = $(this).val();
            if(typingText != "" && typingText.length > 2){
                // typing text is not empty
                $("#extensionValidationMessage").html("Checking..");
                $("#extensionValidationMessage").css("color", "black");  
                $("#btnSaveExtension").addClass("disabled");

                $.ajax({
                    url: "<?= Url::to(['admin/checkextensionavailability'])?>",
                    data: {typingExtension : typingText},
                    type: 'GET',
                    success: function (data, textStatus, jqXHR) {
                        if(data == "1"){
                            // extension is available
                            $("#extensionValidationMessage").html("Extension is available");
                            $("#extensionValidationMessage").css("color", "green");
                            $("#btnSaveExtension").removeClass("disabled");
                            isExtensionExists = false;
                        }else{
                            // extension is not available
                            $("#extensionValidationMessage").html("Extension is not available");
                            $("#extensionValidationMessage").css("color", "red");  
                            $("#btnSaveExtension").addClass("disabled");
                            isExtensionExists = true;
                        }
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        console.log("extension validation error : "+jqXHR.responseText);
                    	isExtensionExists = true;
                    }
                });    
            }else{
                // typing text is empty
                $("#extensionValidationMessage").html("");
                $("#extensionValidationMessage").css("color", "red");  
                $("#btnSaveExtension").addClass("disabled");
            }
        });
        

</script>

views/supevisor/manageUsers.php
<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php

use yii\helpers\Url;
use yii\helpers\Html;
?>
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
        <style>
            .btn-default{
                background-color: #10297d !important;
                color: #faa61a !important;
            }
            .text-success{
                color: #10297d !important;
            }

        </style>
    </head>
    <body>
        <div class="container-fluid">
            <div class="row" style="margin-top: 1%;">
                <div class="col-md-12">
                    <h3 class="text-left text-success"><strong>
                            Manage Users
                        </strong>
                    </h3>
                </div>
            </div>
            <div class="row">
                <?php
                if(Yii::$app->session->get("user_role") == 1){
                    // user is admin
                ?>    
                    <div class="col-md-2">
                        <a name="btnAddNewUser" id="btnAddNewUser" class="btn btn-default btn-lg" href="<?= Url::to(['supevisor/insert']) ?>">Add New User</a>
                    </div>
                    <div class="col-md-3">
                        <a name="btnAddNewExtensionQueue" id="btnAddNewExtensionQueue" class="btn btn-default btn-lg" href="<?= Url::to(['supevisor/queuecreate'])?>">Add New Extensions Queue</a>
                    </div>
                    <div class="col-md-2">
                        <a name="btnAddNewExtension" id="btnAddNewExtension" class="btn btn-default btn-lg" href="<?= Url::to(['supevisor/addextension'])?>">Add New Extensions</a>
                    </div>
                    <div class="col-md-5">

                    </div>
                <?php    
                }else{
                    // user is not admin
                ?>
                    <div class="col-md-2">
                        <a name="btnAddNewUser" id="btnAddNewUser" class="btn btn-default btn-lg" href="<?= Url::to(['supevisor/insert']) ?>">Add New User</a>
                    </div>
                    <div class="col-md-10">

                    </div>                
                
                <?php
                }
                ?>

            </div>
            <br>
            <br>


        </div>
        <div class="row" style="margin-top: 3%;" id="userTableFrame">
            Loading users list...

        </div>
        <script>
            $(document).ready(function () {
                $('#userTableFrame').load("<?php echo Url::to(['supevisor/managetable']) ?>");
            });
        </script>
    </body>
</html>