models/User.php
<?php

namespace app\models;

class User extends \yii\base\Object implements \yii\web\IdentityInterface
{
    public $id;
    public $username;
    public $password;
    public $authKey;
    public $accessToken;

    private static $users = [
        '100' => [
            'id' => '100',
            'username' => 'admin',
            'password' => 'admin',
            'authKey' => 'test100key',
            'accessToken' => '100-token',
        ],
        '101' => [
            'id' => '101',
            'username' => 'demo',
            'password' => 'demo',
            'authKey' => 'test101key',
            'accessToken' => '101-token',
        ],
    ];


    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return isset(self::$users[$id]) ? new static(self::$users[$id]) : null;
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        foreach (self::$users as $user) {
            if (strcasecmp($user['username'], $username) === 0) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return $this->password === $password;
    }
}

controllers/UserController.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of LoginController
 *
 * @since 2017-06-26
 * @author Prabath
 * 
 */

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\call_center_user;
use app\models\customer;
use yii\helpers\Url;
use yii\helpers\FileHelper;
use app\models\Agent_requests;
use app\models\Logged_in_users;
use app\models\Dnd_records;
use app\models\Extension_queue;
use app\models\Ext_queue_intermediate;
use DateTime;
use app\models\Deleted_call_center_user;

class UserController extends Controller {

    public function actionLogin_view() {
        $session = Yii::$app->session;
        if (!$session->has('user_id')) {
            return $this->render('userLogin');
        } else {
            $user_role = $session->get('user_role');
            if ($user_role == '1' || $user_role == '3') {
                $this->redirect('index.php?r=supevisor/overview');
            } else if ($user_role == '2' || $user_role == '4') {
                $this->redirect('index.php?r=agent/callerinformation');
            }else if ($user_role == '5') {
                $this->redirect('index.php?r=reports/supervisorreports');
            }
        }
    }

    public function actionVerifytext() {
        $users = call_center_user::find();

        Yii::$app->request->post();
        $post = Yii::$app->request->post('loginForm');

        $user_name = $_POST['user_name'];
        $selectedUserRole = $_POST['hiddenSelectedUserRoleInput'];
        $password = $_POST['password'];
        $hashedPassword = md5($password);

        //check username.if exists get password.
        $dbuser = $users
                ->where("name = '$user_name'") //   
                ->andWhere("status = 'active'")
                ->all();

        if ($dbuser) {
            $dbpassword = $dbuser[0]['password'];

            if ($dbpassword == $hashedPassword) {
                // user logged in successfully   

                $user_role = $dbuser[0]['role_id'];
                
                if($user_role == '3' && Extension_queue::isSupervisorAssignedToAnExtensionQueue($dbuser[0]['id']) == FALSE){
                    return 2; // the user is a supervisor but has no extension queue assigned to him, returns 2
                }
                
                
                $session = Yii::$app->session;
                $session->set('user_id', $dbuser[0]['id']);
                $session->set('user_name', $dbuser[0]['name']);
                $session->set('full_name', $dbuser[0]['fullname']);
                $session->set('user_role', $dbuser[0]['role_id']);
                $session->set('access_time', time());
                $session->set('voip', $dbuser[0]['voip_extension']);

                Logged_in_users::setOldRecordInactive($dbuser[0]['id']);
                Logged_in_users::insertNewRecordForLogin($dbuser[0]['id'], $_SERVER['REMOTE_ADDR']);


                if ($user_role == '1' || $user_role == '3') {
                    // logged in user is a admin or supervisor
                    $session->set('dnd', true); // This means default DND is ON
                    
                    
                    if($user_role == '3'){
                        // user is a supervisor
                        $session->set('extQueueId', Extension_queue::getExtensionQueueIdOfTheSupervisor($dbuser[0]['id'])); // This is to keep the extension queue id belongs to the supervisor
                    }
                    
                    
                    if ($selectedUserRole == 1) {
                        // user selected to show the supervisor dashboard
                        $this->redirect('index.php?r=supevisor/overview');
                    }else if ($selectedUserRole == 4) {
                        $this->redirect('index.php?r=reports/supervisorreports');                        
                    }else{
                        // show the supervisor the agent dashbord
                        $this->redirect('index.php?r=agent/callerinformation');
                    }
                } else if ($user_role == '2') {
                    // logged in user is an agent
                    $session->set('dnd', false); // This means default DND is OFF
                    $session->set('extQueueId', Ext_queue_intermediate::getExtensionQueueIdOfVOIPExtension($dbuser[0]['voip_extension'])); // This is to keep the extension queue id belongs to the agent

                    if ($this->checkIfagentislate($dbuser[0]['id']) == TRUE) {
                        // agent is late
                        $this->redirect('index.php?r=agent/callerinformation&late');
                    } else {
                        // agent is not late
                        $this->redirect('index.php?r=agent/callerinformation');
                    }
                } else if ($user_role == '4') {
                    // logged in user is a super agent
                    $session->set('dnd', false); // This means default DND is OFF
                    $session->set('extQueueId', Ext_queue_intermediate::getExtensionQueueIdOfVOIPExtension($dbuser[0]['voip_extension'])); // This is to keep the extension queue id belongs to the agent

//                    $this->redirect("index.php?r=superuser/dashboard");
                    $this->redirect('index.php?r=agent/callerinformation');
                } else if ($user_role == '5') {
                    // logged in user is a executive    
                    $session->set('dnd', true);
                    if ($selectedUserRole == 1) {
                        $hadSupervisorAccess = Extension_queue::find()->where(['supervisor_id'=> Yii::$app->session->get('user_id')])->one();
                        if ($hadSupervisorAccess != null) {
                            $session->set('extQueueId', Extension_queue::getExtensionQueueIdOfTheSupervisor($dbuser[0]['id'])); // This is to keep the extension queue id belongs to the supervisor
                            $this->redirect('index.php?r=supevisor/overview');                            
                        }else{
                            $this->redirect('index.php?r=reports/supervisorreports');                            
                        }
                    }

                    if ($selectedUserRole == 4) {
                        $this->redirect('index.php?r=reports/supervisorreports');
                    }

                }
            } else {
                return 0;
            }
        } else {
            return 0;
        }
    }

    /**
     * 
     * @return type
     * 
     * @modified Sandun 2017-12-19
     * @description removes the extQueueId element from the session when logs out
     */
    public function actionLogout(){
        $session = Yii::$app->session;
        $session->remove('user_id');
        $session->remove('user_name');
        $session->remove('user_role');
        $session->remove('voip');
        $session->remove('dnd');
        $session->remove('extQueueId');
        return $this->render('userLogin');
    }

    private function checkIfagentislate($agentId) {
        $takenBreak = Agent_requests::getTakenBreaks($agentId);
        if ($takenBreak) {
            //has a taken break
            $breakTakenTime = $takenBreak['taken_time'];
            $breakDuration = $takenBreak['approved_time_period'];
            $breakOverTime = date("Y-m-d H:i:s", strtotime("+$breakDuration minutes", strtotime($breakTakenTime)));
            $reLoggedTime = date("Y-m-d H:i:s");

            if (strtotime($reLoggedTime) > strtotime($breakOverTime)) {
                // the agent is late
                Agent_requests::setBreakRequestConsumed($takenBreak['id']);
                return TRUE;
            } else {
                // agent is not late
                return FALSE;
            }
        } else {
            // dont have a taken break
            return FALSE;
        }
    }

    /**
     * <b>Set DND status in the session</b>
     * <p>This function updates the session state for the DND mode of the agent</p>
     * 
     * @author Sandun
     * @since 2017-08-01
     * @return boolean
     * 
     * @modified Sandun 2017-09-25
     * @description Added a session check, if there is no user id set to the active session, user will be redirected to the login page
     */
    public function actionSetdndsessionstate() {
        if (!Yii::$app->session->has('user_id')) {
            $this->redirect('index.php?r=user/login_view');
        }

        $state = $_GET['state'];
        if ($state == 1) {
            // DND is ON
            $this->setDNDStateinDB("On");
            Yii::$app->session->set('dnd', true);
            echo 1;
        } else {
            // DND is OFF
            $this->setDNDStateinDB("Off");
            Yii::$app->session->set('dnd', false);
            echo 0;
        }
    }

    /**
     * 
     * 
     * @modified Sandun 2017-09-25
     * @description Added a session check, if there is no user id set to the active session, user will be redirected to the login page
     */
    public function actionGetagentinfofromvoipext() {
        if (!Yii::$app->session->has('user_id')) {
            $this->redirect('index.php?r=user/login_view');
        }
        $extensionNumber = $_POST['extension'];
        $agentInformation = call_center_user::getUserInfoFromVOIPExtension($extensionNumber);
        if (count($agentInformation) > 0) {
            $agentInformationJson = array();
            $agentInformationJson['id'] = $agentInformation['id'];
            $agentInformationJson['name'] = $agentInformation['name'];
            $agentInformationJson['fullname'] = $agentInformation['fullname'];
            $agentInformationJson['user_profile_pic'] = $agentInformation['user_profile_pic'];

views/user/userLogin.php
<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?php

use yii\helpers\Url;
$params = require(__DIR__ . '../../../config/view_parameters.php');

?>
<style>
    .navbar-inverse{
        display: none;
    }

    .navbar-fixed-top{
        display: none;
    }
    .wrlogo{
        height: 100px;
    }
    .login-body{
        background-color: #ffffff;
        border: 3px solid #fbad18;
        border-radius: 5px;
        padding-top: 4%;padding-bottom: 5%;
    }
    body{
        background-color: rgb(29, 76, 161);
    }
</style>
<script>
    $(function () {

        $(".dropdown-menu li a").click(function () {

            $(".user-role-dropdown-btn:first-child").text($(this).text());
            $(".user-role-dropdown-btn:first-child").val($(this).text());
        });

    });
</script>

<div class="container login-body" style="">
    <div class="row" style="">
        <div class="col-xs-5"></div>
        <div class="col-xs-2"><img class="img-responsive" src="<?=$params['login_image_url'];?>"></div>
        <div class="col-xs-5"></div>
    </div><br>
    <div class="row" style="">
        <div class="col-xs-3"></div>
        <div class="col-xs-6" style="font-size: 110%; text-align: center">Logging in to <span style="color: #00a;font-weight: bold"><?=$params['logging_into_text'];?></span> call center software.</div>
        <div class="col-xs-3"></div>
    </div><br>
    <div class="row" style="">
        <div class="col-xs-4"></div>
        <div class="col-xs-4">

            <form id="loginForm" name="loginForm" >
                <fieldset>                    
                    <div class="form-group">
                        <!--<span class="notificationSpan" style="display: none;color: red;"><span class="noifyText">Invalid username or password</span></span>-->
                        <div style=" display: none; width: 100%" class="alert alert-danger" id="invalidCredentialsAlertDiv">
                            <strong>Invalid username or password!</strong> Please check
                        </div>
                        <div style="display: none; width: 100%" class="alert alert-warning" id="missingCredentialsAlertDiv">
                            <strong>Please insert your username, password and select your role!</strong>
                        </div>
                        <div style="display: none; width: 100%" class="alert alert-info" id="queueNotAssignedAlertDiv">
                            <strong>You have not yet assigned to a queue. Please contact your administrator!</strong>
                        </div>
                    </div>
                    <div class="dropdown form-group">
                        <button style="text-align: left" class="user-role-dropdown-btn btn btn-block btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Select User Role
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" style="width: 100%">
                            <li><a href="#" onclick="$('#hiddenSelectedUserRoleInput').val(1)">Supervisor</a></li>
                            <li><a href="#" onclick="$('#hiddenSelectedUserRoleInput').val(2)">Super User</a></li>
                            <li><a href="#" onclick="$('#hiddenSelectedUserRoleInput').val(3)">Agent</a></li>
                            <li><a href="#" onclick="$('#hiddenSelectedUserRoleInput').val(4)">Executive</a></li>

                        </ul>
                        <input style="display: none" id="hiddenSelectedUserRoleInput" name="hiddenSelectedUserRoleInput" value="0">
                    </div>                    
<!--                    <div class="form-group">
                        <label style="font-size: 100%;" for="user_name">VOIP Extension</label>                        
                        <input class="form-control loginFields" title="You can enter your VOIP Extention and login." name="voipExtensionInput" type="number" id="voipExtensionInput" autofocus style="display: none">
                        <select id="selectVoipExtension" name="selectVoipExtension" class="form-control" title="Select your VOIP extension" onchange="$('#voipExtensionInput').val($(this).val())">
                            <option value="">Select your VOIP extension</option>
                            <option value="800">800</option>
                            <option value="801">801</option>
                            <option value="802">802</option>
                            <option value="803">803</option>
                            <option value="804">804</option>
                            <option value="805">805</option>
                            <option value="806">806</option>
                            <option value="807">807</option>
                            <option value="808">808</option>
                            <option value="809">809</option>
                            <option value="810">810</option>
                        </select>
                    </div>-->
                    <div class="form-group">
                        <label style="font-size: 110%;" for="user_name">Username</label>
                        <input class="form-control loginFields" name="user_name" type="text" id="user_name" autofocus>
                    </div>
                    <div class="form-group">
                        <label style="font-size: 110%;" for="password">Password</label>
                        <input class="form-control loginFields" name="password" type="password" id="id_password" onkeypress="pressEnter(event)">
                    </div>
                    <div class="form-group"><a class="btn btn-block btn-primary loginbutton" style="border: 1px solid black" name="btnSubmit" id="btnSubmit" onclick="triggerEvent(event);">Log in</a></div>
                </fieldset>
                <br>
                <div class="alert alert-warning" style="display: none" id="warningMessageDiv">
                    <strong id="warningMessageHead"></strong> <p id="warningMessageBody"></p>
                </div>
                <div class="alert alert-danger" style="display: none" id="failMessageDiv">
                    <strong id="failMessageHead"></strong> <p id="failMessageBody"></p>
                </div>
            </form>

            <script>
                function pressEnter(event) {
                    if (event.keyCode == 13) {
                        triggerEvent(event);
                    }
                }// end of pressEnter function 

            </script>
            <script>
                function triggerEvent(e) {
                    $("#missingCredentialsAlertDiv").css("display", "none");
                    $("#invalidCredentialsAlertDiv").css("display", "none");

                    var url = "<?= Url::to(['user/verifytext']) ?>"; // the script where you handle the form input.
                    if ($('#user_name').val() != '' && $('#id_password').val() != '' && $('#hiddenSelectedUserRoleInput').val() != 0)
                    {
                        $.ajax({
                            type: "POST",
                            url: url,
                            data: $("#loginForm").serialize(), // serializes the form's elements.
                            success: function (data)
                            {
                                $(".notificationSpan").fadeOut();
                                if (data == "1") {
                                    $('#btnSubmit').css("background-color", "#00b300");
                                    $('#btnSubmit').css("color", "black");

                                    setTimeout(function () {
                                        location.reload();
                                    }, 1000);
                                } else if(data == "2"){
                                    $("#missingCredentialsAlertDiv").css("display", "none");
                                    $("#invalidCredentialsAlertDiv").css("display", "none");
                                    $("#queueNotAssignedAlertDiv").css("display", "block");
                                }else {
//                                    $(".notificationSpan").css("display", "inline");//.fadeOut(5000);
                                    $("#missingCredentialsAlertDiv").css("display", "none");
                                    $("#queueNotAssignedAlertDiv").css("display", "none");
                                    $("#invalidCredentialsAlertDiv").css("display", "block");
                                }
                            },
                            error: function (xhr, ajaxOptions, thrownError) {

                            }

                        });
                    } else if ($('#user_name').val() != '' && $('#id_password').val() != '' && $('#hiddenSelectedUserRoleInput').val() == 0) {
                        $("#invalidCredentialsAlertDiv").css("display", "none");
                        $("#missingCredentialsAlertDiv > strong").html("Please select your role!");
                        $("#missingCredentialsAlertDiv").css("display", "block");
                    } else {
//                        $(".notificationSpan").css("display", "inline");
                        $("#invalidCredentialsAlertDiv").css("display", "none");
                        $("#missingCredentialsAlertDiv > strong").html("Please insert your username, password and select your role!");
                        $("#missingCredentialsAlertDiv").css("display", "block");
                    }
                    e.preventDefault(); // avoid to execute the actual submit of the form.
                }


            </script>
        </div>
        <div class="col-xs-12" style="font-size: 110%; text-align: center">Go to <a href="#" onclick="window.open('<?= $params['ccDashboradUrlLoginPage'] ?>', '_blank');"><span style="color: #16a900;font-weight: bold"><?=$params['ccDashboradName'];?></span></a></div>
        <div class="col-xs-4 col-lg-4"></div>
    </div>
</div>